# Generated by Django 4.0.5 on 2023-07-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Puede visualizar el catálogo de vehículos'), ('agregar_vehiculo', 'Puede agregar un nuevo vehículo')]},
        ),
    ]
